### ISSUE TITLE
Unable to install Natural 0.9 

### ISSUE THREAD

**Issue by Vijay73786** [rlogiacco/Natural#93]
When clicked on install and hit confirm -> got the popup saying : Unable to read repository at http://rlogiacco.github.com/Natural.
http://rlogiacco.github.com/Natural is not a valid repository location.

**Comment by nathanmobbs** [comment]
> Installs: 266K (**6 last month**)

Looks like you're not the only one having this issue.

**Comment by TestLeafInc** [comment]
Use http://rlogiacco.github.io/Natural

**Comment by lakshmikanth-1712** [comment]
Use http://rlogiacco.github.io/Natural
This URL works perfectly fine.. Thanks!!

**Comment by nikhilgosavi19** [comment]
http://rlogiacco.github.io/Natural
This URL is no longer working:(

**Comment by naveenjotron** [comment]
can't install from Eclipse marketplace.
http://rlogiacco.github.com/Natural is not a valid repository location.

**Comment by rlogiacco** [comment]
You know lads, this is an open-source project: rather than complaining about stuff you got for free and is not working, you could provide solutions...

**Comment by dassusovan** [comment]
Help -> Install New Software 
![image](https://user-images.githubusercontent.com/32001700/154521869-15adbf33-8b47-4326-b66c-4182df805a01.png)

**Comment by rlogiacco** [comment]
Fixed by #95

**Comment by JACKRULER** [comment]
stil its not working http://rlogiacco.github.com/Natural

**Comment by JACKRULER** [comment]
any updates to install the same

**Comment by dheerajkumard009** [comment]
Still Not Working  http://rlogiacco.github.com/Natural 
Kindly Provide The Solution Without that plug in Some  off  the features is not getting imported

**Comment by Lucky5E9** [comment]
Try http://rlogiacco.github.io/Natural

This will work for sure Just now I tried.

Thanks.

**Comment by Lucky5E9** [comment]
> Still Not Working http://rlogiacco.github.com/Natural Kindly Provide The Solution Without that plug in Some off the features is not getting imported

http://rlogiacco.github.com/Natural

try this

**Comment by DhanuMeenu** [comment]
http://rlogiacco.github.com/Natural worked now

**Comment by suryavasudev** [comment]
https://rlogiacco.github.io/Natural :  .io extension is working but this URL is not working in any browsers. you can install it in eclipse itself by clicking help- Install new software- click Add - Name : Natural, Location : https://rlogiacco.github.io/Natural then click Add.
